//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpTraining {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSON {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSON() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpTraining.JSON", typeof(JSON).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;id&quot;: 12,
        ///	&quot;CreationDate&quot;: &quot;12/03/2015&quot;,
        ///	&quot;ClientName&quot;: &quot;Paula Castellanos&quot;,
        ///	&quot;products&quot;: [{
        ///		&quot;name&quot;: &quot;Cracking the Coding Interview, 6th Edition: 189 Programming Questions and Solutions&quot;,
        ///		&quot;unitPrice&quot;: 28.67,
        ///		&quot;quantity&quot;: 3
        ///	},
        ///	{
        ///		&quot;name&quot;: &quot;Introduction to Algorithms, 3rd Edition&quot;,
        ///		&quot;unitPrice&quot;: 66.32,
        ///		&quot;quantity&quot;: 10
        ///	},
        ///	{
        ///		&quot;name&quot;: &quot;Starting Out with C++ from Control Structures to Objects (8th Edition)&quot;,
        ///		&quot;unitPrice&quot;: 134.18,
        ///		&quot;quantity&quot;: 13
        ///	},
        ///	{
        ///		&quot;name&quot;: &quot;HTML and CSS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
    }
}
